const THEME_TOKENS = {
  "co-working-default": {
    primaryColor: "#1A1A2E",
    accentColor: "#4F46E5",
    bgColor: "#F8F9FA",
    textColor: "#212529",
    fontMood: "modern",
    layoutDensity: "spacious",
    borderRadius: "rounded",
  },
  "co-living-default": {
    primaryColor: "#2D4A3E",
    accentColor: "#52B788",
    bgColor: "#F0F7F4",
    textColor: "#1B2D25",
    fontMood: "warm",
    layoutDensity: "spacious",
    borderRadius: "rounded",
  },
  "workation-default": {
    primaryColor: "#1B3A5C",
    accentColor: "#F4A261",
    bgColor: "#FAFAFA",
    textColor: "#1C1C1E",
    fontMood: "bold",
    layoutDensity: "balanced",
    borderRadius: "rounded",
  },
  "hostel-default": {
    primaryColor: "#3D2B1F",
    accentColor: "#E76F51",
    bgColor: "#FFF8F5",
    textColor: "#2C1810",
    fontMood: "playful",
    layoutDensity: "compact",
    borderRadius: "pill",
  },
  "meeting-rooms-default": {
    primaryColor: "#0D1B2A",
    accentColor: "#1F7A8C",
    bgColor: "#F4F6F8",
    textColor: "#0D1B2A",
    fontMood: "minimal",
    layoutDensity: "spacious",
    borderRadius: "sharp",
  },
  "cafe-default": {
    primaryColor: "#3E2723",
    accentColor: "#D4A017",
    bgColor: "#FDF6EC",
    textColor: "#2C1A0E",
    fontMood: "warm",
    layoutDensity: "balanced",
    borderRadius: "pill",
  },
};

module.exports = { THEME_TOKENS };
