import React from "react";
import { Reveal, Stagger } from "../motion";
import { groupOpeningHours, highlightLines } from "../templateKit";
import { LeadFormPanel } from "../shared/TplLead";
import { MessageForm } from "../shared/TplForms";
import { FaqSection } from "../shared/TplParts";
import { useTpl } from "../shared/TplContext";
import { Placeholder, StarRow } from "../shared/TplUI";
const img = (value) => (typeof value === "string" ? value : value?.url || "");
const Hero = ({ eyebrow, title, intro }) => (<section><div className="tp-wrap pb-10 pt-10 md:pb-14 md:pt-14"><Reveal><p className="mb-4 text-[11px] font-bold uppercase tracking-[.18em]">{eyebrow}</p><h1 className="max-w-5xl text-[clamp(56px,9vw,126px)] leading-[.84]">{title}</h1>{intro ? <p className="tp-muted mt-7 max-w-2xl text-[16px] leading-8">{intro}</p> : null}</Reveal></div></section>);
const Reviews = () => {
    const { t } = useTpl();
    if (!t.testimonials.length)
        return null;
    return <section className="tp-section"><div className="tp-wrap"><p className="mb-3 text-[11px] font-bold uppercase tracking-[.18em]">Reviews</p><h2 className="text-[clamp(42px,6vw,78px)]">Happy customers</h2><Stagger className="mt-12 grid gap-8 md:grid-cols-2">{t.testimonials.slice(0, 4).map((item, index) => <figure key={item.key || index} className="trv-review"><StarRow value={item.rating || 5}/><blockquote className="mt-5 text-[18px] leading-8">{item.text}</blockquote><figcaption className="mt-6 text-[11px] font-bold uppercase tracking-[.14em]">{item.name}</figcaption></figure>)}</Stagger></div></section>;
};
export const TravigoAbout = () => {
    const { t, draft } = useTpl();
    const photos = (Array.isArray(draft?.aboutPageImages) ? draft.aboutPageImages : []).map(img).filter(Boolean);
    const images = photos.length ? photos : t.galleryItems;
    const story = t.aboutIntroBlocks;
    const founders = t.founders;
    return <><Hero eyebrow="About us" title={draft?.aboutTitle || "About us"} intro={story[0]}/><section className="tp-wrap pb-16"><div className="grid grid-cols-2 gap-6 border-y py-8 md:grid-cols-4">{[["12k+", "Happy guests"], [`${Math.max(t.testimonials.length, 15)}+`, `Guest stories`], [`${Math.max(t.galleryItems.length, 24)}+`, `Local moments`], ["24/7", "Guest support"]].map(([value, label]) => <div key={label}><p className="trv-number">{value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.14em] opacity-50">{label}</p></div>)}</div></section><section className="tp-section"><div className="tp-wrap grid items-center gap-12 md:grid-cols-2 md:gap-20"><Reveal>{images[0] ? <div className="trv-round-media aspect-square"><img src={images[0]} alt=""/></div> : <Placeholder text="Our story"/>}</Reveal><div><Reveal><p className="mb-4 text-[11px] font-bold uppercase tracking-[.18em]">Our story</p><h2 className="text-[clamp(42px,6vw,78px)] leading-[.94]">{draft?.aboutPageStory || "Made by travellers, for travellers."}</h2></Reveal>{story.slice(1).map((text, index) => <Reveal key={index} delay={.08 + index * .04}><p className="tp-muted mt-6 text-[16px] leading-8">{text}</p></Reveal>)}</div></div></section><section className="trv-cta tp-section"><div className="tp-wrap grid gap-12 md:grid-cols-[1fr_1.1fr] md:gap-20"><Reveal><p className="mb-4 text-[11px] font-bold uppercase tracking-[.18em] text-white/55">Affordable travel</p><h2 className="text-[clamp(44px,7vw,90px)] leading-[.9]">Unforgettable experiences.</h2></Reveal><div className="space-y-9">{t.aboutNarrativeBlocks.map((block, index) => <Reveal key={block.title} delay={index * .05}><div className="border-t border-white/20 pt-5"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-white/45">0{index + 1}</p><h3 className="mt-3 text-[28px]">{block.title}</h3><p className="mt-3 text-[15px] leading-7 text-white/65">{block.body}</p></div></Reveal>)}</div></div></section>{founders.length ? <section className="tp-section"><div className="tp-wrap"><h2 className="mb-10 text-[clamp(42px,6vw,72px)]">Meet your hosts</h2><Stagger className="grid gap-8 md:grid-cols-2">{founders.map((founder, index) => <article key={index} className="grid gap-5 border-t pt-5 sm:grid-cols-[160px_1fr]"><div className="aspect-square overflow-hidden rounded-full">{founder.image ? <img src={img(founder.image)} alt={founder.name} className="h-full w-full object-cover"/> : <Placeholder text={founder.name}/>}</div><div><h3 className="text-[28px]">{founder.name}</h3><p className="text-[11px] font-bold uppercase tracking-[.14em] opacity-50">{founder.role}</p>{founder.bio ? <p className="tp-muted mt-4 text-[14px] leading-7">{founder.bio}</p> : null}{highlightLines(founder.highlights).map((line) => <p key={line} className="mt-2 text-sm font-semibold">{line}</p>)}</div></article>)}</Stagger></div></section> : null}<Reviews /></>;
};
export const TravigoGallery = () => { const { t, draft } = useTpl(); return <><Hero eyebrow="Gallery" title={draft?.galleryPageHeading || "Travel moments"} intro="A look at the rooms, shared spaces and places around us."/><section className="tp-wrap pb-20"><div className="grid auto-rows-[180px] grid-cols-2 gap-4 md:auto-rows-[240px] md:grid-cols-4">{t.galleryItems.map((src, index) => <Reveal key={`${src}-${index}`} className={index % 7 === 0 ? "col-span-2 row-span-2" : index % 5 === 2 ? "row-span-2" : ""}><button type="button" className={`tp-zoom h-full w-full overflow-hidden ${index % 4 === 1 ? "rounded-[999px_999px_0_0]" : index % 4 === 3 ? "rounded-[0_0_999px_999px]" : ""}`} onClick={() => t.openGalleryViewer(index)}><img src={src} alt="" loading="lazy"/></button></Reveal>)}</div></section></>; };
export const TravigoTestimonials = () => { const { t, draft, rating } = useTpl(); return <><Hero eyebrow="Reviews" title={draft?.testimonialsPageHeading || "Happy customers"} intro={draft?.testimonialsPageIntro}/><section className="tp-wrap pb-20"><div className="mb-12 flex items-end justify-between border-y py-7"><div><p className="trv-number">{rating.count ? rating.avg.toFixed(1) : "5.0"}</p><StarRow value={rating.avg || 5}/></div>{t.showWriteReview ? <button type="button" className="tp-btn tp-btn-primary" onClick={t.openReviewModal}>Write a review</button> : null}</div><Stagger className="grid gap-x-8 gap-y-12 md:grid-cols-2">{t.testimonials.map((item, index) => <figure key={item.key || index} className="trv-review"><StarRow value={item.rating || 5}/><blockquote className="mt-5 text-[20px] leading-8">{item.text}</blockquote><figcaption className="mt-6 text-[11px] font-bold uppercase tracking-[.14em]">{item.name}{item.role ? <span className="font-normal opacity-50"> · {item.role}</span> : null}</figcaption></figure>)}</Stagger></section></>; };
export const TravigoPartner = () => { const { t, draft } = useTpl(); const paragraphs = String(t.partnerPageContent || "").split("\n").filter(Boolean); return <><Hero eyebrow="Partnerships" title={t.partnerPageHeading || `Partner with ${draft?.companyName || "us"}`} intro={paragraphs[0]}/><section className="tp-wrap grid gap-12 pb-20 md:grid-cols-[.9fr_1.1fr] md:gap-20"><div className="space-y-6">{paragraphs.slice(1).map((line, index) => <p key={index} className="tp-muted text-[16px] leading-8">{line}</p>)}</div><div className="border-y py-8"><h2 className="mb-7 text-[32px]">{t.partnerFormTitle || "Get in touch"}</h2><MessageForm inquiryType="Partnership" submitLabel="Send to our team" success="We've received your note and will be in touch soon."/></div></section></>; };
export const TravigoContact = () => { const { t, draft, primary } = useTpl(); const hours = groupOpeningHours(draft?.openingHours); const showForm = draft?.contactEnableInquiryForm !== false; const image = t.galleryItems[1] || t.heroImages?.[1] || ""; return <><Hero eyebrow="Contact us" title={draft?.contactPageHeading || "Get in touch"} intro={draft?.contactPageIntro}/><section className="tp-wrap grid gap-10 pb-20 lg:grid-cols-[.8fr_1.2fr] lg:gap-20">{image ? <Reveal className="trv-round-media min-h-[460px]"><img src={image} alt="" className="h-full w-full object-cover"/></Reveal> : null}<div>{showForm ? <div className="border-y py-8"><h2 className="mb-7 text-[32px]">{primary?.leadEnabled ? primary.profile.labels.leadTitle : "Send us a message"}</h2>{primary?.leadEnabled ? <LeadFormPanel service={primary}/> : <MessageForm inquiryType="General Enquiry" submitLabel="Send message" success={draft?.contactInquirySuccessMessage || "Thank you. Your inquiry has been submitted successfully."}/>}</div> : null}<div className="mt-10 grid gap-8 sm:grid-cols-2">{t.contactAddress ? <div><p className="text-[10px] font-bold uppercase tracking-[.14em] opacity-50">Office address</p><p className="mt-3 text-[16px] leading-7">{t.contactAddress}</p></div> : null}{t.contactEmail ? <div><p className="text-[10px] font-bold uppercase tracking-[.14em] opacity-50">Chat to support</p><a className="mt-3 block text-[16px]" href={`mailto:${t.contactEmail}`}>{t.contactEmail}</a></div> : null}{t.contactPhone ? <div><p className="text-[10px] font-bold uppercase tracking-[.14em] opacity-50">Call us</p><a className="mt-3 block text-[16px]" href={`tel:${String(t.contactPhone).replace(/[^\d+]/g, "")}`}>{t.contactPhone}</a></div> : null}{hours.length ? <div><p className="text-[10px] font-bold uppercase tracking-[.14em] opacity-50">Hours</p><ul className="mt-3 space-y-1 text-[14px]">{hours.map((row) => <li key={row.days}>{row.days}: {row.hours}</li>)}</ul></div> : null}</div></div></section>{draft?.mapUrl ? <section className="tp-wrap pb-20"><Reveal><div className="trv-map-shell"><div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] opacity-50">Find us</p><h2 className="text-[clamp(34px,5vw,60px)] leading-none">Right where the trip begins.</h2></div>{t.contactAddress ? <p className="tp-muted max-w-sm text-sm leading-6 md:text-right">{t.contactAddress}</p> : null}</div><iframe title={`${draft?.companyName || "Hostel"} location map`} src={draft.mapUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="h-[340px] w-full border-0 md:h-[480px]"/></div></Reveal></section> : null}<FaqSection faqs={draft?.faqs}/><Reviews /></>; };
