// Maps country names (as produced by the `country-state-city` package, which
// is what HostPanel's Workspace Setup uses) to their continent. HostPanel
// never asks the host for a continent, so most Host Company records have it
// blank — Nomads' Company schema requires `continent`, so this is used as a
// fallback wherever a company's continent isn't already set.
const COUNTRY_TO_CONTINENT = {
  Afghanistan: "Asia",
  "Aland Islands": "Europe",
  Albania: "Europe",
  Algeria: "Africa",
  "American Samoa": "Oceania",
  Andorra: "Europe",
  Angola: "Africa",
  Anguilla: "North America",
  Antarctica: "Antarctica",
  "Antigua And Barbuda": "North America",
  Argentina: "South America",
  Armenia: "Asia",
  Aruba: "North America",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  "The Bahamas": "North America",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "North America",
  Belarus: "Europe",
  Belgium: "Europe",
  Belize: "North America",
  Benin: "Africa",
  Bermuda: "North America",
  Bhutan: "Asia",
  Bolivia: "South America",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  "Bouvet Island": "Antarctica",
  Brazil: "South America",
  "British Indian Ocean Territory": "Africa",
  Brunei: "Asia",
  Bulgaria: "Europe",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  Cambodia: "Asia",
  Cameroon: "Africa",
  Canada: "North America",
  "Cape Verde": "Africa",
  "Cayman Islands": "North America",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Chile: "South America",
  China: "Asia",
  "Christmas Island": "Oceania",
  "Cocos (Keeling) Islands": "Oceania",
  Colombia: "South America",
  Comoros: "Africa",
  Congo: "Africa",
  "Democratic Republic of the Congo": "Africa",
  "Cook Islands": "Oceania",
  "Costa Rica": "North America",
  "Cote D'Ivoire (Ivory Coast)": "Africa",
  Croatia: "Europe",
  Cuba: "North America",
  Cyprus: "Europe",
  "Czech Republic": "Europe",
  Denmark: "Europe",
  Djibouti: "Africa",
  Dominica: "North America",
  "Dominican Republic": "North America",
  "East Timor": "Asia",
  Ecuador: "South America",
  Egypt: "Africa",
  "El Salvador": "North America",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Estonia: "Europe",
  Ethiopia: "Africa",
  "Falkland Islands": "South America",
  "Faroe Islands": "Europe",
  "Fiji Islands": "Oceania",
  Finland: "Europe",
  France: "Europe",
  "French Guiana": "South America",
  "French Polynesia": "Oceania",
  "French Southern Territories": "Antarctica",
  Gabon: "Africa",
  "The Gambia": "Africa",
  Georgia: "Asia",
  Germany: "Europe",
  Ghana: "Africa",
  Gibraltar: "Europe",
  Greece: "Europe",
  Greenland: "North America",
  Grenada: "North America",
  Guadeloupe: "North America",
  Guam: "Oceania",
  Guatemala: "North America",
  "Guernsey and Alderney": "Europe",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Guyana: "South America",
  Haiti: "North America",
  "Heard Island and McDonald Islands": "Antarctica",
  Honduras: "North America",
  "Hong Kong S.A.R.": "Asia",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  Israel: "Asia",
  Italy: "Europe",
  Jamaica: "North America",
  Japan: "Asia",
  Jersey: "Europe",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kiribati: "Oceania",
  "North Korea": "Asia",
  "South Korea": "Asia",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  "Macau S.A.R.": "Asia",
  Macedonia: "Europe",
  Madagascar: "Africa",
  Malawi: "Africa",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mali: "Africa",
  Malta: "Europe",
  "Man (Isle of)": "Europe",
  "Marshall Islands": "Oceania",
  Martinique: "North America",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Mexico: "North America",
  Micronesia: "Oceania",
  Moldova: "Europe",
  Monaco: "Europe",
  Mongolia: "Asia",
  Montenegro: "Europe",
  Montserrat: "North America",
  Morocco: "Africa",
  Mozambique: "Africa",
  Myanmar: "Asia",
  Namibia: "Africa",
  Nauru: "Oceania",
  Nepal: "Asia",
  "Bonaire, Sint Eustatius and Saba": "North America",
  Netherlands: "Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Nicaragua: "North America",
  Niger: "Africa",
  Nigeria: "Africa",
  Niue: "Oceania",
  "Norfolk Island": "Oceania",
  "Northern Mariana Islands": "Oceania",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Palau: "Oceania",
  "Palestinian Territory Occupied": "Asia",
  Panama: "North America",
  "Papua new Guinea": "Oceania",
  Paraguay: "South America",
  Peru: "South America",
  Philippines: "Asia",
  "Pitcairn Island": "Oceania",
  Poland: "Europe",
  Portugal: "Europe",
  "Puerto Rico": "North America",
  Qatar: "Asia",
  Reunion: "Africa",
  Romania: "Europe",
  Russia: "Europe",
  Rwanda: "Africa",
  "Saint Helena": "Africa",
  "Saint Kitts And Nevis": "North America",
  "Saint Lucia": "North America",
  "Saint Pierre and Miquelon": "North America",
  "Saint Vincent And The Grenadines": "North America",
  "Saint-Barthelemy": "North America",
  "Saint-Martin (French part)": "North America",
  Samoa: "Oceania",
  "San Marino": "Europe",
  "Sao Tome and Principe": "Africa",
  "Saudi Arabia": "Asia",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Singapore: "Asia",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Solomon Islands": "Oceania",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Georgia": "Antarctica",
  "South Sudan": "Africa",
  Spain: "Europe",
  "Sri Lanka": "Asia",
  Sudan: "Africa",
  Suriname: "South America",
  "Svalbard And Jan Mayen Islands": "Europe",
  Swaziland: "Africa",
  Sweden: "Europe",
  Switzerland: "Europe",
  Syria: "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  Tanzania: "Africa",
  Thailand: "Asia",
  Togo: "Africa",
  Tokelau: "Oceania",
  Tonga: "Oceania",
  "Trinidad And Tobago": "North America",
  Tunisia: "Africa",
  Turkey: "Asia",
  Turkmenistan: "Asia",
  "Turks And Caicos Islands": "North America",
  Tuvalu: "Oceania",
  Uganda: "Africa",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "North America",
  "United States Minor Outlying Islands": "Oceania",
  Uruguay: "South America",
  Uzbekistan: "Asia",
  Vanuatu: "Oceania",
  "Vatican City State (Holy See)": "Europe",
  Venezuela: "South America",
  Vietnam: "Asia",
  "Virgin Islands (British)": "North America",
  "Virgin Islands (US)": "North America",
  "Wallis And Futuna Islands": "Oceania",
  "Western Sahara": "Africa",
  Yemen: "Asia",
  Zambia: "Africa",
  Zimbabwe: "Africa",
  Kosovo: "Europe",
  Curaçao: "North America",
  "Sint Maarten (Dutch part)": "North America",
};

const getContinentForCountry = (country) => {
  const normalized = String(country || "").trim();
  if (!normalized) return "";
  return COUNTRY_TO_CONTINENT[normalized] || "";
};

module.exports = { getContinentForCountry };
